syntax="proto3";
package user;

service UserService {
    rpc GetUser(GetUserRequest) returns(UserResponse);
    rpc CreateUser(CreateUserRequest) returns(UserResponse);
    rpc UpdateUser(UpdateUserRequest) returns(UserResponse);
    rpc DeleteUser(DeleteUserRequest) returns(UserResponse);
}

type UserResponse struct {
    id int32;
    name string;
    email string;
}

type GetUserRequest struct {
    id int32;
}

type CreateuserRequest struct {
    name string;
    email string;
}

type UpdateUserRequest struct {
    id int32;
    name string;
    email string;
}

type DeleteUserRequest struct {
    id int32;
}